/**
 * AGV model matching Django backend (vda5050/models.py)
 * Represents a physical Automated Guided Vehicle in the fleet
 */
export interface Agv {
  id?: number // Auto-generated by Django
  manufacturer: string // e.g., "KUKA", max 100 chars
  serial_number: string // Unique serial number, max 100 chars
  description?: string // Optional description
  protocol_version?: string // VDA5050 protocol version, e.g., "2.1.0"
  current_map_id?: string // Current map ID, max 100 chars
  is_online?: boolean // Auto-managed by backend
  last_seen?: string // ISO timestamp, auto-managed by backend
}
