# Generated by Django 5.2.9 on 2025-12-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AGV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("is_online", models.BooleanField(default=False)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AGVState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("header_id", models.IntegerField()),
                ("order_id", models.CharField(max_length=100, null=True)),
                ("last_node_id", models.CharField(max_length=100, null=True)),
                ("driving", models.BooleanField(default=False)),
                ("battery_state", models.JSONField(default=dict)),
                ("agv_position", models.JSONField(default=dict, null=True)),
                ("errors", models.JSONField(default=list)),
                (
                    "agv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vda5050.agv"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, unique=True)),
                ("order_update_id", models.IntegerField(default=0)),
                ("nodes", models.JSONField(default=list)),
                ("edges", models.JSONField(default=list)),
                ("status", models.CharField(default="CREATED", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="vda5050.agv",
                    ),
                ),
            ],
        ),
    ]
