# Generated by Django 5.2.9 on 2025-12-22 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vda5050", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agv",
            options={"verbose_name": "AGV", "verbose_name_plural": "AGV Fleet"},
        ),
        migrations.AddField(
            model_name="agv",
            name="current_map_id",
            field=models.CharField(
                blank=True,
                help_text="Current map in use by the AGV",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agv",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agv",
            name="protocol_version",
            field=models.CharField(
                blank=True,
                help_text="Supported VDA version (e.g., 2.1.0)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agvstate",
            name="information",
            field=models.JSONField(
                default=dict, help_text="Other debug information", null=True
            ),
        ),
        migrations.AddField(
            model_name="agvstate",
            name="last_node_sequence_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agvstate",
            name="loads",
            field=models.JSONField(
                default=list, help_text="Current loads being carried"
            ),
        ),
        migrations.AddField(
            model_name="agvstate",
            name="operating_mode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="agvstate",
            name="paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agvstate",
            name="received_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Time when the Server received it",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agvstate",
            name="safety_state",
            field=models.JSONField(default=dict, help_text="{eStop, fieldViolation}"),
        ),
        migrations.AddField(
            model_name="agvstate",
            name="velocity",
            field=models.JSONField(
                default=dict, help_text="{vx, vy, omega}", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="header_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason why the AGV rejected this order",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="zone_set_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="agv",
            name="is_online",
            field=models.BooleanField(
                default=False, help_text="MQTT connection status"
            ),
        ),
        migrations.AlterField(
            model_name="agv",
            name="manufacturer",
            field=models.CharField(
                help_text="Manufacturer (e.g., KUKA)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="agv",
            name="serial_number",
            field=models.CharField(
                help_text="Unique serial number of the AGV", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="agvstate",
            name="agv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="vda5050.agv",
            ),
        ),
        migrations.AlterField(
            model_name="agvstate",
            name="agv_position",
            field=models.JSONField(
                default=dict, help_text="{x, y, theta, mapId...}", null=True
            ),
        ),
        migrations.AlterField(
            model_name="agvstate",
            name="battery_state",
            field=models.JSONField(
                default=dict, help_text="{charge, voltage, health...}"
            ),
        ),
        migrations.AlterField(
            model_name="agvstate",
            name="errors",
            field=models.JSONField(default=list, help_text="List of current errors"),
        ),
        migrations.AlterField(
            model_name="agvstate",
            name="last_node_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="agvstate",
            name="order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="agvstate",
            name="timestamp",
            field=models.DateTimeField(
                help_text="Time when the AGV created the packet"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="edges",
            field=models.JSONField(default=list, help_text="List of Edges"),
        ),
        migrations.AlterField(
            model_name="order",
            name="nodes",
            field=models.JSONField(
                default=list, help_text="List of Nodes (with Actions)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                help_text="Unique order ID from VDA", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_update_id",
            field=models.IntegerField(
                default=0, help_text="Used for updating/extending orders"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Newly Created"),
                    ("SENT", "Sent to AGV"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected by AGV"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED", "Failed"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agv",
            unique_together={("manufacturer", "serial_number")},
        ),
        migrations.AddIndex(
            model_name="agvstate",
            index=models.Index(
                fields=["agv", "timestamp"], name="vda5050_agv_agv_id_02e87b_idx"
            ),
        ),
    ]
