# Generated by Django 5.2.9 on 2025-12-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vda5050", "0003_instantaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instantaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("startPause", "Pause"),
                    ("stopPause", "Resume"),
                    ("cancelOrder", "Cancel"),
                ],
                max_length=50,
            ),
        ),
    ]
