# Generated by Django 5.2.12 on 2026-03-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vda5050", "0005_graphnode_graphedge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphedge",
            name="length",
            field=models.FloatField(help_text="Length of the edge (m)"),
        ),
        migrations.AlterField(
            model_name="graphedge",
            name="max_velocity",
            field=models.FloatField(
                default=1.0, help_text="Maximum allowed velocity (m/s)"
            ),
        ),
        migrations.AlterField(
            model_name="graphnode",
            name="node_id",
            field=models.CharField(
                help_text="Unique identifier for the point", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="graphnode",
            name="theta",
            field=models.FloatField(
                default=0.0, help_text="Orientation angle of the vehicle at this point"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Newly Created"),
                    ("SENT", "Sent to AGV"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected by AGV"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED", "Failed"),
                    ("QUEUED", "Queued for Sending"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
