# Generated by Django 5.2.12 on 2026-03-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vda5050', '0006_alter_graphedge_length_alter_graphedge_max_velocity_and_more'),
    ]

    operations = [
    ]
