# Generated by Django 5.2.12 on 2026-04-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vda5050', '0006_graphnode_node_type_alter_graphedge_length_and_more'),
        ('vda5050', '0008_alter_graphedge_length'),
    ]

    operations = [
    ]
