persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Cho phép kết nối từ bên ngoài container (quan trọng)
listener 1883
allow_anonymous true
# WebSocket listener for frontend
listener 9001
protocol websockets
allow_anonymous true
